# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dock_compositePlots.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_compositePlots(object):
    def setupUi(self, compositePlots):
        compositePlots.setObjectName("compositePlots")
        compositePlots.resize(447, 247)
        compositePlots.setMinimumSize(QtCore.QSize(400, 200))
        self.dockWidget_plotsCompositeContents = QtWidgets.QWidget(compositePlots)
        self.dockWidget_plotsCompositeContents.setGeometry(QtCore.QRect(20, 20, 400, 200))
        self.dockWidget_plotsCompositeContents.setMinimumSize(QtCore.QSize(400, 200))
        self.dockWidget_plotsCompositeContents.setObjectName("dockWidget_plotsCompositeContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidget_plotsCompositeContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_1 = QtWidgets.QFrame(self.dockWidget_plotsCompositeContents)
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_1)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame_1)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_1, 0, 0, 1, 1)
        self.widget = PlotWidget(self.dockWidget_plotsCompositeContents)
        self.widget.setObjectName("widget")
        self.gridLayout_2.addWidget(self.widget, 0, 1, 1, 1)

        self.retranslateUi(compositePlots)
        QtCore.QMetaObject.connectSlotsByName(compositePlots)

    def retranslateUi(self, compositePlots):
        _translate = QtCore.QCoreApplication.translate
        compositePlots.setWindowTitle(_translate("compositePlots", "Plots"))
        self.label.setText(_translate("compositePlots", "Composite name :"))
        self.label_2.setText(_translate("compositePlots", "Parameter :"))
        self.label_3.setText(_translate("compositePlots", "Sub-Parameter :"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    compositePlots = QtWidgets.QWidget()
    ui = Ui_compositePlots()
    ui.setupUi(compositePlots)
    compositePlots.show()
    sys.exit(app.exec_())
