# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dock_physicalObject.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PhysicalObject(object):
    def setupUi(self, PhysicalObject):
        PhysicalObject.setObjectName("PhysicalObject")
        PhysicalObject.resize(550, 218)
        self.dockWidget_physicalObjectContents = QtWidgets.QWidget(PhysicalObject)
        self.dockWidget_physicalObjectContents.setGeometry(QtCore.QRect(9, 9, 531, 191))
        self.dockWidget_physicalObjectContents.setObjectName("dockWidget_physicalObjectContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dockWidget_physicalObjectContents)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.dockWidget_physicalObjectContents)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.dockWidget_physicalObjectContents)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3.addWidget(self.widget_2, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.dockWidget_physicalObjectContents)
        self.frame_2.setMinimumSize(QtCore.QSize(513, 80))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_next = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_next.setMaximumSize(QtCore.QSize(160, 23))
        self.pushButton_next.setObjectName("pushButton_next")
        self.gridLayout.addWidget(self.pushButton_next, 1, 2, 1, 1)
        self.pushButton_preview = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_preview.setMinimumSize(QtCore.QSize(160, 23))
        self.pushButton_preview.setObjectName("pushButton_preview")
        self.gridLayout.addWidget(self.pushButton_preview, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(161, 23))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout.addWidget(self.frame_3, 1, 1, 1, 1)
        self.pushButton_browserModelFile = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_browserModelFile.setMinimumSize(QtCore.QSize(160, 23))
        self.pushButton_browserModelFile.setObjectName("pushButton_browserModelFile")
        self.gridLayout.addWidget(self.pushButton_browserModelFile, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 2, 0, 1, 1)

        self.retranslateUi(PhysicalObject)
        QtCore.QMetaObject.connectSlotsByName(PhysicalObject)

    def retranslateUi(self, PhysicalObject):
        _translate = QtCore.QCoreApplication.translate
        PhysicalObject.setWindowTitle(_translate("PhysicalObject", "Physical Object"))
        self.label.setText(_translate("PhysicalObject", "TextLabel"))
        self.pushButton_next.setText(_translate("PhysicalObject", "Next"))
        self.pushButton_preview.setText(_translate("PhysicalObject", "Preview"))
        self.pushButton_browserModelFile.setText(_translate("PhysicalObject", "Open model"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PhysicalObject = QtWidgets.QWidget()
    ui = Ui_PhysicalObject()
    ui.setupUi(PhysicalObject)
    PhysicalObject.show()
    sys.exit(app.exec_())
